name: Run Python script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai python-dotenv

    - name: Check .env file
      run: cat .env

    - name: Run Python script
      run: python quiz_interactif.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
