name: Generate Quiz and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Exécute le workflow tous les jours à minuit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate quiz questions
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python quiz_interactif.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        exclude_assets: ''
